title: SAELZLER.COM
subtitle: Welcome to the World Wide Web
description: The blog and web home page of Vincent Saelzler.
locale: en

url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed

exclude: # items are added to the internal "default list".
  - LICENSE.txt
  - README.md

theme: minimal-mistakes-jekyll
date_format: "%-d %B, %Y"
atom_feed:
  hide: true

author:
  name     : "Vincent Saelzler"
  avatar   : "/assets/images/vince.jpg"
  bio      : "Some Guy with a Website"
  location : "London, UK"
  github: VincentSaelzler
  linkedin: VincentSaelzler
