title: "Vince's Website"
subtitle: Welcome to the World Wide Web
description: The blog and web home of Vincent Saelzler.
locale: en

url: "https://vincent.saelzler.com"

plugins:
  - jekyll-feed

include: ["_pages"]

exclude: # items are added to the internal "default list".
  - LICENSE.txt
  - README.md

theme: minimal-mistakes-jekyll
date_format: "%-d %B, %Y"
atom_feed:
  hide: true


collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single



author:
  name     : "Vincent Saelzler"
  avatar   : "/assets/images/vince.jpg"
  bio      : "Some Guy with a Website"
  location : "London, UK"
  github: VincentSaelzler
  linkedin: VincentSaelzler
