title: Vincent Saelzler
logo: "/assets/images/yin-yang.png"
subtitle: Data Professional
description: The blog and web home of Vincent Saelzler.
locale: en
url: "https://vincent.saelzler.com"

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

exclude: # items are added to the internal "default list".
  - LICENSE.txt
  - README.md

date_format: "%Y-%m-%d"

collections:
  quotes:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      # no filter, i.e. all paths
      path: ""
    values:
      layout: single
      # classes: wide

# https://mmistakes.github.io/minimal-mistakes/docs/pages/


# author:
#   name     : "Vincent Saelzler"
#   avatar   : "/assets/images/vince.jpg"
#   bio      : "Some Guy with a Website"
#   location : "London, UK"
#   github: VincentSaelzler
#   linkedin: VincentSaelzler

# running bundle exec jekyll serve
# there were lots of deprication warnings
# which make it hard to see real problems
sass:
  quiet_deps: true
